### ISSUE TITLE
[ Issue ] Safari project hover outline

### ISSUE THREAD

**Issue by vincentchoqueuse** [Polo-Wolo/hugo-enib#8]
Sur Safari, l'apparence des "cards" dans la section Projects n'est pas super harmonieuse avec l'attribut hover (bordure carrée). 

<img width="442" alt="Capture d’écran 2023-01-24 à 18 55 42" src="https://user-images.githubusercontent.com/5786355/214370838-3755f308-0ceb-40cd-a266-b71e9b7ed6e1.png">

**Comment by Polo-Wolo** [comment]
essayer : 
https://tailwindcss.com/docs/ring-width

**Comment by vincentchoqueuse** [comment]
commit: 1f0eafddf904a2c604801316357e58947ffbf894

**Comment by Polo-Wolo** [comment]
box-shadow: inset 0 0 0 3px var(--clr-sfr2);
